version: '3'
services:
  keycloak:
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    image: quay.io/keycloak/keycloak:20.0.3
    command: start-dev
